sudo: false

language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '9'

before_script:
  - npm prune

script:
  - npm run clean
  - npm run build

after_script: 
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run deploy; fi 
